export enum SmsStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  UNDELIVERED = 'UNDELIVERED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  FATAL_FAILURE = 'FATAL_FAILURE',
}
